name: SIT
on:
  workflow_run:
    workflows: PreApproval
    types:
      - completed
  workflow_dispatch:
  
jobs:
  Build:
    name: Build Npm project
    runs-on: ubuntu-latest
    steps:    
    - name : Build
      run: echo "deployment"
