name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Change to your default branch if needed
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: hehe
        uses: docker/login-action@v2
        with:
          username: sgulhane
          password: dckr_pat_V0RvQkYrFBDUdwO8dtcOf_M6IWg
      - name:
        run : |
         docker pull nginx:latest
         docker tag nginx:latest sgulhane/automation:v1
         docker push sgulhane/automation

      - name: Log out from Docker Hub
        run: docker logout
