name: PreApproval
on: workflow_dispatch
jobs:
  Build:
    name: CreateBranch
    runs-on: ubuntu-latest
    steps:    
    - name : echo
      run: echo "deployment"
    - name: Checkout repository​
      uses: actions/checkout@v2​
    - name: push
      run: |
       git checkout -b release/2024.1​
       git push origin release/​2024.1​
​
      


